from __future__ import annotations

from typing import Any

from picos.modeling import Constraint as Constraint
from picos.modeling import Problem as Problem

class Expression:
    @property
    def H(self) -> ComplexAffineExpression: ...
    def __add__(self, other: Expression | float | complex) -> Expression: ...
    def __radd__(self, other: float | complex) -> Expression: ...
    def __truediv__(self, other: float | complex) -> Expression: ...
    def __eq__(self, other: object) -> Constraint: ...
    def __rshift__(self, other: Any) -> Constraint: ...

class ComplexAffineExpression(Expression): ...
class AffineExpression(ComplexAffineExpression): ...

class SymmetricVariable(AffineExpression):
    def __init__(self, name: str, size: int) -> None: ...
    def __getitem__(self, index: tuple[int, int]) -> AffineExpression: ...

class HermitianVariable(ComplexAffineExpression):
    def __init__(self, name: str, size: int) -> None: ...
    def __getitem__(self, index: tuple[int, int]) -> ComplexAffineExpression: ...

def block(matrix: Any) -> AffineExpression: ...
