from __future__ import annotations

from typing import Literal, Self, TypeAlias, TypeVar, overload

from .. import Polynomial

Scalar = TypeVar("Scalar", float, complex)

class CommutativeOperator:
    @overload
    def __add__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __add__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __add__(self, other: CommutativePolynomialElement) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __add__(
        self, other: Polynomial[CommutativePolynomialElement, Scalar]
    ) -> Polynomial[CommutativePolynomialElement, Scalar]: ...
    @overload
    def __radd__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __radd__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __sub__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __sub__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __sub__(self, other: CommutativePolynomialElement) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __sub__(
        self, other: Polynomial[CommutativePolynomialElement, Scalar]
    ) -> Polynomial[CommutativePolynomialElement, Scalar]: ...
    @overload
    def __rsub__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __rsub__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __mul__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __mul__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __mul__(self, other: CommutativePolynomialElement) -> CommutativeMonomial: ...
    @overload
    def __mul__(
        self, other: Polynomial[CommutativePolynomialElement, Scalar]
    ) -> Polynomial[CommutativePolynomialElement, Scalar]: ...
    @overload
    def __rmul__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __rmul__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __truediv__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __truediv__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __neg__(self) -> RealCoefficientsCommutativePolynomial: ...
    def __pow__(self, power: int) -> CommutativeMonomial: ...
    def __hash__(self) -> int: ...
    def conjugate(self) -> Self: ...

class CommutativeMonomial:
    @overload
    def __add__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __add__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __add__(self, other: CommutativePolynomialElement) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __add__(
        self, other: Polynomial[CommutativePolynomialElement, Scalar]
    ) -> Polynomial[CommutativePolynomialElement, Scalar]: ...
    @overload
    def __radd__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __radd__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __sub__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __sub__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __sub__(self, other: CommutativePolynomialElement) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __sub__(
        self, other: Polynomial[CommutativePolynomialElement, Scalar]
    ) -> Polynomial[CommutativePolynomialElement, Scalar]: ...
    @overload
    def __rsub__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __rsub__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __mul__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __mul__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __mul__(self, other: CommutativePolynomialElement) -> CommutativeMonomial: ...
    @overload
    def __mul__(
        self, other: Polynomial[CommutativePolynomialElement, Scalar]
    ) -> Polynomial[CommutativePolynomialElement, Scalar]: ...
    @overload
    def __rmul__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __rmul__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    @overload
    def __truediv__(self, other: float) -> RealCoefficientsCommutativePolynomial: ...
    @overload
    def __truediv__(self, other: complex) -> ComplexCoefficientsCommutativePolynomial: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __neg__(self) -> RealCoefficientsCommutativePolynomial: ...
    def __pow__(self, power: int) -> CommutativeMonomial: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def conjugate(self) -> Self: ...

CommutativePolynomialElement: TypeAlias = CommutativeMonomial | CommutativeOperator

class CommutativePolynomial(Polynomial[CommutativePolynomialElement, Scalar]):
    def conjugate(self) -> Self: ...

RealCoefficientsCommutativePolynomial: TypeAlias = CommutativePolynomial[float]
ComplexCoefficientsCommutativePolynomial: TypeAlias = CommutativePolynomial[complex]

@overload
def generate_commutative_variables(
    label: str,
    number: int,
    *,
    moment_matrix_id: int = 0,
    starting_index: int = 0,
    real: bool = False,
    projector: bool = False,
    return_identity: Literal[False] = False,
) -> list[CommutativeOperator]: ...
@overload
def generate_commutative_variables(
    label: str,
    number: int,
    *,
    moment_matrix_id: int = 0,
    starting_index: int = 0,
    real: bool = False,
    projector: bool = False,
    return_identity: Literal[True],
) -> tuple[list[CommutativeOperator], CommutativeMonomial]: ...

__all__ = ["generate_commutative_variables"]
