"""Type stubs for ``picos.expressions``, PICOS 2.6.2.

Recovered from the installed package: the class hierarchy from ``__mro__``,
constructor signatures from ``inspect.signature``, and the result type of every
operator by evaluating it in a shell against real variables.

A note on real vs. complex. PICOS decides at runtime, from the *values* it is
handed, whether the result of an operation is an ``AffineExpression`` (real) or
a ``ComplexAffineExpression``; the choice is not visible in the operand types.
The overloads below therefore keep the result real only when the operand is
statically real -- another real expression, a ``float``, or constant data whose
dtype is unknown but real in practice -- and widen to complex as soon as a
``complex`` or an already-complex expression is involved. That matches what
PICOS actually returned for every operator this project uses.
"""

from abc import ABC
from collections.abc import Iterable, Sequence
from typing import Any, TypeAlias, overload

import numpy.typing as npt
from scipy.sparse import sparray, spmatrix

from picos.constraints import Constraint
from picos.valuable import Valuable

# Constant operands. PICOS funnels these through
# `picos.expressions.data.load_data`, which takes Python scalars, (nested)
# sequences, NumPy arrays, CVXOPT matrices and SciPy sparse matrices. CVXOPT is
# untyped and so is covered by the `Sequence`/`Any` arms rather than named.
_RealData: TypeAlias = float | Sequence[Any] | npt.NDArray[Any] | spmatrix | sparray
_Data: TypeAlias = complex | _RealData

class Expression(Valuable, ABC):
    @property
    def string(self) -> str: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def dim(self) -> int: ...
    @property
    def refined(self) -> Expression: ...
    @property
    def variables(self) -> frozenset[BaseVariable]: ...
    @property
    def mutables(self) -> frozenset[Mutable]: ...
    @property
    def constant(self) -> bool: ...
    @property
    def scalar(self) -> bool: ...
    @property
    def square(self) -> bool: ...
    @property
    def convex(self) -> bool: ...
    @property
    def concave(self) -> bool: ...
    def __add__(self, other: Expression | _Data) -> Expression: ...
    def __radd__(self, other: _Data) -> Expression: ...
    def __sub__(self, other: Expression | _Data) -> Expression: ...
    def __rsub__(self, other: _Data) -> Expression: ...
    def __mul__(self, other: Expression | _Data) -> Expression: ...
    def __rmul__(self, other: _Data) -> Expression: ...
    def __matmul__(self, other: Expression | _Data) -> Expression: ...
    def __rmatmul__(self, other: _Data) -> Expression: ...
    def __truediv__(self, other: Expression | _Data) -> Expression: ...
    def __or__(self, other: Expression | _Data) -> Expression: ...
    def __xor__(self, other: Expression | _Data) -> Expression: ...
    def __pow__(self, other: Expression | _Data) -> Expression: ...
    def __neg__(self) -> Expression: ...
    def __abs__(self) -> Expression: ...
    def __getitem__(self, index: Any) -> Expression: ...
    # The comparison operators build constraints rather than booleans, which is
    # incompatible with `object.__eq__` by construction, hence the ignore.
    def __eq__(self, other: Expression | _Data) -> Constraint: ...  # ty: ignore[invalid-method-override]
    def __le__(self, other: Expression | _Data) -> Constraint: ...
    def __ge__(self, other: Expression | _Data) -> Constraint: ...
    # Loewner order (matrix inequality) / set membership.
    def __rshift__(self, other: Expression | _Data) -> Constraint: ...
    def __lshift__(self, other: Expression | _Data) -> Constraint: ...
    def __hash__(self) -> int: ...

class BiaffineExpression(Expression):
    @property
    def real(self) -> Expression: ...
    @property
    def imag(self) -> Expression: ...
    @property
    def conj(self) -> Expression: ...
    @property
    def T(self) -> Expression: ...
    @property
    def H(self) -> Expression: ...
    @property
    def isreal(self) -> bool: ...
    # "Whether the expression can be complex-valued" -- a `cached_property` returning `bool`, not the
    # complex value of the expression.
    @property
    def complex(self) -> bool: ...
    @property
    def is0(self) -> bool: ...
    @property
    def is1(self) -> bool: ...
    @property
    def isI(self) -> bool: ...
    def __getitem__(self, index: Any) -> BiaffineExpression: ...

class ComplexAffineExpression(BiaffineExpression):
    @property
    def real(self) -> AffineExpression: ...
    @property
    def imag(self) -> AffineExpression: ...
    @property
    def conj(self) -> ComplexAffineExpression: ...
    @property
    def T(self) -> ComplexAffineExpression: ...
    @property
    def H(self) -> ComplexAffineExpression: ...
    def __add__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    def __radd__(self, other: _Data) -> ComplexAffineExpression: ...
    def __sub__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    def __rsub__(self, other: _Data) -> ComplexAffineExpression: ...
    def __mul__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    def __rmul__(self, other: _Data) -> ComplexAffineExpression: ...
    def __matmul__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    def __rmatmul__(self, other: _Data) -> ComplexAffineExpression: ...
    def __truediv__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    def __or__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    def __xor__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    def __neg__(self) -> ComplexAffineExpression: ...
    def __getitem__(self, index: Any) -> ComplexAffineExpression: ...
    def __hash__(self) -> int: ...

class AffineExpression(ComplexAffineExpression):
    # `real`, `conj` and `H` are the identity (or plain transpose) on a real
    # affine expression, so they stay in this class.
    @property
    def real(self) -> AffineExpression: ...
    @property
    def imag(self) -> AffineExpression: ...
    @property
    def conj(self) -> AffineExpression: ...
    @property
    def T(self) -> AffineExpression: ...
    @property
    def H(self) -> AffineExpression: ...
    @overload
    def __add__(self, other: AffineExpression | _RealData) -> AffineExpression: ...
    @overload
    def __add__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    @overload
    def __radd__(self, other: _RealData) -> AffineExpression: ...
    @overload
    def __radd__(self, other: _Data) -> ComplexAffineExpression: ...
    @overload
    def __sub__(self, other: AffineExpression | _RealData) -> AffineExpression: ...
    @overload
    def __sub__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    @overload
    def __rsub__(self, other: _RealData) -> AffineExpression: ...
    @overload
    def __rsub__(self, other: _Data) -> ComplexAffineExpression: ...
    @overload
    def __mul__(self, other: AffineExpression | _RealData) -> AffineExpression: ...
    @overload
    def __mul__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    @overload
    def __rmul__(self, other: _RealData) -> AffineExpression: ...
    @overload
    def __rmul__(self, other: _Data) -> ComplexAffineExpression: ...
    @overload
    def __matmul__(self, other: AffineExpression | _RealData) -> AffineExpression: ...
    @overload
    def __matmul__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    @overload
    def __truediv__(self, other: AffineExpression | _RealData) -> AffineExpression: ...
    @overload
    def __truediv__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    @overload
    def __or__(self, other: AffineExpression | _RealData) -> AffineExpression: ...
    @overload
    def __or__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    @overload
    def __xor__(self, other: AffineExpression | _RealData) -> AffineExpression: ...
    @overload
    def __xor__(self, other: Expression | _Data) -> ComplexAffineExpression: ...
    def __neg__(self) -> AffineExpression: ...
    def __getitem__(self, index: Any) -> AffineExpression: ...
    def __hash__(self) -> int: ...

class QuadraticExpression(Expression): ...
class UncertainExpression(Expression): ...
class UncertainAffineExpression(UncertainExpression): ...

class Constant(AffineExpression):
    def __init__(self, name_or_value: Any, value: Any = ..., shape: int | tuple[int, int] | None = ...) -> None: ...

# ---------------------------------------------------------------------------
# Mutables and variables
#
# Runtime bases, from `RealVariable.__bases__`:
#   RealVariable(BaseVariable, AffineExpression), BaseVariable(Mutable),
#   Mutable(ABC).
# ---------------------------------------------------------------------------

class Mutable(ABC):
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @property
    def internal_value(self) -> Any: ...
    def copy(self, new_name: str | None = ...) -> Mutable: ...

# `Mutable` alone is not a `Valuable` at runtime, but every instantiable
# variable is: they are all declared as `(BaseVariable, <some affine
# expression>)`, and the expression side brings `Valuable` in. `BaseVariable` is
# abstract, so listing `Valuable` among its bases here describes every variable
# object that can actually exist -- and it is what lets `Problem.get_variable`,
# whose return PICOS types as the base class, expose `.value`. The resulting MRO
# matches the runtime one.
class BaseVariable(Mutable, Valuable):
    @property
    def bound_dual(self) -> Any: ...

class RealVariable(BaseVariable, AffineExpression):
    def __init__(
        self,
        name: str,
        shape: int | tuple[int, int] = ...,
        lower: Any = ...,
        upper: Any = ...,
    ) -> None: ...

class ComplexVariable(BaseVariable, ComplexAffineExpression):
    def __init__(self, name: str, shape: int | tuple[int, int] = ...) -> None: ...

class SymmetricVariable(BaseVariable, AffineExpression):
    def __init__(
        self,
        name: str,
        shape: int | tuple[int, int] = ...,
        lower: Any = ...,
        upper: Any = ...,
    ) -> None: ...

class HermitianVariable(BaseVariable, ComplexAffineExpression):
    # Unlike the other three, PICOS gives `shape` no default here.
    def __init__(self, name: str, shape: int | tuple[int, int]) -> None: ...

class SkewSymmetricVariable(BaseVariable, AffineExpression):
    def __init__(self, name: str, shape: int | tuple[int, int] = ...) -> None: ...

class LowerTriangularVariable(BaseVariable, AffineExpression):
    def __init__(self, name: str, shape: int | tuple[int, int] = ..., lower: Any = ..., upper: Any = ...) -> None: ...

class UpperTriangularVariable(BaseVariable, AffineExpression):
    def __init__(self, name: str, shape: int | tuple[int, int] = ..., lower: Any = ..., upper: Any = ...) -> None: ...

class IntegerVariable(BaseVariable, AffineExpression):
    def __init__(self, name: str, shape: int | tuple[int, int] = ..., lower: Any = ..., upper: Any = ...) -> None: ...

class BinaryVariable(BaseVariable, AffineExpression):
    def __init__(self, name: str, shape: int | tuple[int, int] = ...) -> None: ...

CONTINUOUS_VARTYPES: tuple[type[BaseVariable], ...]

# ---------------------------------------------------------------------------
# Algebra (`picos.expressions.algebra`, re-exported at the package top level)
# ---------------------------------------------------------------------------

@overload
def sum(lst: Iterable[AffineExpression] | AffineExpression, axis: int | None = ...) -> AffineExpression: ...
@overload
def sum(lst: Iterable[Expression | _Data] | Expression, axis: int | None = ...) -> ComplexAffineExpression: ...
@overload
def trace(x: AffineExpression) -> AffineExpression: ...
@overload
def trace(x: Expression | _Data) -> ComplexAffineExpression: ...
def block(
    nested: Iterable[Iterable[Expression | _Data]],
    shapes: Any = ...,
    name: str | None = ...,
) -> AffineExpression: ...
def diag(x: Expression | _Data, n: int = ...) -> AffineExpression: ...
def diag_vect(x: Expression | _Data, offset: int = ...) -> AffineExpression: ...
def maindiag(x: Expression | _Data) -> AffineExpression: ...
def kron(*args: Expression | _Data) -> ComplexAffineExpression: ...
def partial_trace(x: Expression | _Data, subsystems: Any = ..., dimensions: Any = ...) -> ComplexAffineExpression: ...
def partial_transpose(
    x: Expression | _Data, subsystems: Any = ..., dimensions: Any = ...
) -> ComplexAffineExpression: ...
def new_param(name: str, value: Any) -> Constant: ...
def exp(x: Expression | _Data) -> Expression: ...
def log(x: Expression | _Data) -> Expression: ...
def norm(x: Expression | _Data, *args: Any, **kwargs: Any) -> Expression: ...
def max(x: Any) -> Expression: ...  # noqa: A001
def min(x: Any) -> Expression: ...  # noqa: A001

# Constant shorthands PICOS exposes at the top level.
I: Constant
J: Constant
O: Constant  # noqa: E741

class Norm(Expression): ...
class SquaredNorm(Expression): ...
class SpectralNorm(Expression): ...
class NuclearNorm(Expression): ...
class SumExponentials(Expression): ...
class LogSumExp(Expression): ...
class Logarithm(Expression): ...
class Entropy(Expression): ...
class NegativeEntropy(Expression): ...
class GeometricMean(Expression): ...
class DetRootN(Expression): ...
class PowerTrace(Expression): ...
class SumExtremes(Expression): ...
class Set(ABC): ...
class Ball(Set): ...
class Ellipsoid(Set): ...
class Simplex(Set): ...
class Cone(Set): ...
class NonnegativeOrthant(Cone): ...
class PositiveSemidefiniteCone(Cone): ...
class SecondOrderCone(Cone): ...
class RotatedSecondOrderCone(Cone): ...
class ExponentialCone(Cone): ...
class ProductCone(Cone): ...
class ZeroSpace(Cone): ...
class TheField(Cone): ...
class Samples: ...
class ExpressionType: ...
class SetType: ...
