from __future__ import annotations

from typing import Literal, Self, TypeAlias, TypeVar, overload

from .. import Polynomial

Scalar = TypeVar("Scalar", float, complex)

class NonCommutativeOperator:
    @overload
    def __add__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __add__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __add__(self, other: NonCommutativePolynomialElement) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __add__(
        self, other: Polynomial[NonCommutativePolynomialElement, Scalar]
    ) -> Polynomial[NonCommutativePolynomialElement, Scalar]: ...
    @overload
    def __radd__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __radd__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __sub__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __sub__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __sub__(self, other: NonCommutativePolynomialElement) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __sub__(
        self, other: Polynomial[NonCommutativePolynomialElement, Scalar]
    ) -> Polynomial[NonCommutativePolynomialElement, Scalar]: ...
    @overload
    def __rsub__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __rsub__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __mul__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __mul__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __mul__(self, other: NonCommutativePolynomialElement) -> NonCommutativeMonomial: ...
    @overload
    def __mul__(
        self, other: Polynomial[NonCommutativePolynomialElement, Scalar]
    ) -> Polynomial[NonCommutativePolynomialElement, Scalar]: ...
    @overload
    def __rmul__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __rmul__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __truediv__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __truediv__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __neg__(self) -> RealCoefficientsNonCommutativePolynomial: ...
    def __pow__(self, power: int) -> NonCommutativeMonomial: ...
    def __hash__(self) -> int: ...
    def adjoint(self) -> Self: ...

class NonCommutativeMonomial:
    @overload
    def __add__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __add__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __add__(self, other: NonCommutativePolynomialElement) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __add__(
        self, other: Polynomial[NonCommutativePolynomialElement, Scalar]
    ) -> Polynomial[NonCommutativePolynomialElement, Scalar]: ...
    @overload
    def __radd__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __radd__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __sub__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __sub__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __sub__(self, other: NonCommutativePolynomialElement) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __sub__(
        self, other: Polynomial[NonCommutativePolynomialElement, Scalar]
    ) -> Polynomial[NonCommutativePolynomialElement, Scalar]: ...
    @overload
    def __rsub__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __rsub__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __mul__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __mul__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __mul__(self, other: NonCommutativePolynomialElement) -> NonCommutativeMonomial: ...
    @overload
    def __mul__(
        self, other: Polynomial[NonCommutativePolynomialElement, Scalar]
    ) -> Polynomial[NonCommutativePolynomialElement, Scalar]: ...
    @overload
    def __rmul__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __rmul__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    @overload
    def __truediv__(self, other: float) -> RealCoefficientsNonCommutativePolynomial: ...
    @overload
    def __truediv__(self, other: complex) -> ComplexCoefficientsNonCommutativePolynomial: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __neg__(self) -> RealCoefficientsNonCommutativePolynomial: ...
    def __pow__(self, power: int) -> NonCommutativeMonomial: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def adjoint(self) -> Self: ...

NonCommutativePolynomialElement: TypeAlias = NonCommutativeMonomial | NonCommutativeOperator

class NonCommutativePolynomial(Polynomial[NonCommutativePolynomialElement, Scalar]):
    def adjoint(self) -> Self: ...

RealCoefficientsNonCommutativePolynomial: TypeAlias = NonCommutativePolynomial[float]
ComplexCoefficientsNonCommutativePolynomial: TypeAlias = NonCommutativePolynomial[complex]

@overload
def generate_noncommutative_variables(
    label: str,
    number: int,
    *,
    moment_matrix_id: int = 0,
    starting_index: int = 0,
    hermitian: bool = False,
    projector: bool = False,
    return_identity: Literal[False] = False,
) -> list[NonCommutativeOperator]: ...
@overload
def generate_noncommutative_variables(
    label: str,
    number: int,
    *,
    moment_matrix_id: int = 0,
    starting_index: int = 0,
    hermitian: bool = False,
    projector: bool = False,
    return_identity: Literal[True],
) -> tuple[list[NonCommutativeOperator], NonCommutativeMonomial]: ...

__all__ = ["generate_noncommutative_variables"]
