"""Type stubs for ``picos.constraints``, PICOS 2.6.2.

Recovered from the installed package: the class hierarchy from ``__mro__`` and
the members from ``vars()`` plus the constructor sources.
"""

from abc import ABC
from typing import Any

from picos.expressions import AffineExpression, ComplexAffineExpression

class Constraint(ABC):
    @property
    def id(self) -> int: ...
    # `dual` is a `cvxopt.base.matrix` for a matrix constraint, a `float` for a
    # scalar one, and `None` before a solution exists. CVXOPT is untyped and the
    # cases are not distinguishable statically, so this is `Any`.
    @property
    def dual(self) -> Any: ...
    @property
    def slack(self) -> Any: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str | None) -> None: ...

class ConicConstraint(Constraint, ABC): ...

# `lhs`, `rhs` and `relation` are instance attributes assigned in the
# constructors of these three classes (`con_affine.py`, `con_lmi.py`) and of the
# quadratic ones (`con_quadratic.py`); they are deliberately absent from the
# `Constraint` base, where PICOS does not define them either. `smaller` and
# `greater` name the two sides by their role in the relation rather than by the
# order they were written in.

class AffineConstraint(ConicConstraint):
    lhs: AffineExpression
    rhs: AffineExpression
    relation: str
    @property
    def smaller(self) -> AffineExpression: ...
    @property
    def greater(self) -> AffineExpression: ...

class ComplexAffineConstraint(ConicConstraint):
    lhs: ComplexAffineExpression
    rhs: ComplexAffineExpression
    relation: str

class LMIConstraint(ConicConstraint):
    lhs: AffineExpression
    rhs: AffineExpression
    relation: str
    @property
    def smaller(self) -> AffineExpression: ...
    @property
    def greater(self) -> AffineExpression: ...

# Note that this derives from `LMIConstraint`, so one `isinstance` check against
# `LMIConstraint` covers both the real and the complex case.
class ComplexLMIConstraint(LMIConstraint): ...
class SOCConstraint(ConicConstraint): ...
class RSOCConstraint(ConicConstraint): ...
class ExpConeConstraint(ConicConstraint): ...
class ProductConeConstraint(ConicConstraint): ...
class DummyConstraint(Constraint): ...
class FlowConstraint(Constraint): ...
class AbsoluteValueConstraint(Constraint): ...
class ConvexQuadraticConstraint(Constraint): ...
class NonconvexQuadraticConstraint(Constraint): ...
class ConicQuadraticConstraint(Constraint): ...
class MatrixNormConstraint(Constraint): ...
class NuclearNormConstraint(Constraint): ...
class GeometricMeanConstraint(Constraint): ...
class DetRootNConstraint(Constraint): ...
class PowerTraceConstraint(Constraint): ...
class LogConstraint(Constraint): ...
class LogSumExpConstraint(Constraint): ...
class KullbackLeiblerConstraint(Constraint): ...
class ExtremumConstraint(Constraint): ...
class SimplexConstraint(Constraint): ...
class ConstraintType: ...
class ConstraintConversion(ABC): ...
