from __future__ import annotations

from enum import Enum
from typing import Generic, Protocol, Self, overload

from ncpoleon._typing import PolynomialElements, Scalar
from ncpoleon.relaxations import Constraint

from .commutative_polynomials import generate_commutative_variables
from .noncommutative_polynomials import generate_noncommutative_variables

class RewritingStrategy(Enum):
    Greedy = 0

# Should be invariant by multiplying and adding within the same vector space
class VectorSpaceElement(Protocol[Scalar]):
    def __add__(self, other: VectorSpaceElement[Scalar]) -> VectorSpaceElement[Scalar]: ...
    def __radd__(self, other: VectorSpaceElement[Scalar]) -> VectorSpaceElement[Scalar]: ...
    def __mul__(self, other: Scalar) -> VectorSpaceElement[Scalar]: ...
    def __rmul__(self, other: Scalar) -> VectorSpaceElement[Scalar]: ...

# FIXME: change _PolynomialsElements to _MonomialType, that don't accept operators. Maybe do this once hybrid
#  polynomials are done
class Polynomial(Generic[PolynomialElements, Scalar]):
    def change_variables(
        self, mapping: dict[PolynomialElements, VectorSpaceElement[Scalar]]
    ) -> VectorSpaceElement[Scalar]: ...
    def by_moment_matrix_id(self) -> dict[int, Polynomial[PolynomialElements, Scalar]]: ...
    def adjoint(self) -> Polynomial[PolynomialElements, Scalar]: ...
    @overload
    def __add__(self, other: float) -> Self: ...
    @overload
    def __add__(self, other: complex) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __add__(self, other: PolynomialElements) -> Self: ...
    @overload
    def __add__(self, other: Polynomial[PolynomialElements, float]) -> Self: ...
    @overload
    def __add__(self, other: Polynomial[PolynomialElements, complex]) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __add__(self, other: Self) -> Self: ...
    @overload
    def __radd__(self, other: float) -> Self: ...
    @overload
    def __radd__(self, other: complex) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __sub__(self, other: float) -> Self: ...
    @overload
    def __sub__(self, other: complex) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __sub__(self, other: PolynomialElements) -> Self: ...
    @overload
    def __sub__(self, other: Polynomial[PolynomialElements, float]) -> Self: ...
    @overload
    def __sub__(self, other: Polynomial[PolynomialElements, complex]) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __sub__(self, other: Self) -> Self: ...
    @overload
    def __rsub__(self, other: float) -> Self: ...
    @overload
    def __rsub__(self, other: complex) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __mul__(self, other: float) -> Self: ...
    @overload
    def __mul__(self, other: complex) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __mul__(self, other: PolynomialElements) -> Self: ...
    @overload
    def __mul__(self, other: Polynomial[PolynomialElements, float]) -> Self: ...
    @overload
    def __mul__(self, other: Polynomial[PolynomialElements, complex]) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __mul__(self, other: Self) -> Self: ...
    @overload
    def __rmul__(self, other: float) -> Self: ...
    @overload
    def __rmul__(self, other: complex) -> Polynomial[PolynomialElements, complex]: ...
    @overload
    def __truediv__(self, other: float) -> Self: ...
    @overload
    def __truediv__(self, other: complex) -> Polynomial[PolynomialElements, complex]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __neg__(self) -> Self: ...
    def __pow__(self, power: int) -> Self: ...
    def degree(self) -> int: ...
    def chop(self, delta: float = ...) -> Self: ...
    def is_zero(self, delta: float | None = None) -> bool: ...
    @overload
    def __eq__(self, other: float) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __eq__(self, other: complex) -> Constraint[PolynomialElements, complex]: ...
    @overload
    def __eq__(self, other: PolynomialElements) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __eq__(self, other: Polynomial[PolynomialElements, float]) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __eq__(
        self,
        other: Polynomial[PolynomialElements, complex]
        ) -> Constraint[PolynomialElements, complex]: ...  # ty: ignore[invalid-method-override]
    @overload
    def __ge__(self, other: float) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __ge__(self, other: complex) -> Constraint[PolynomialElements, complex]: ...
    @overload
    def __ge__(self, other: PolynomialElements) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __ge__(self, other: Polynomial[PolynomialElements, Scalar]) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __ge__(self, other: Polynomial[PolynomialElements, complex]) -> Constraint[PolynomialElements, complex]: ...
    @overload
    def __le__(self, other: float) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __le__(self, other: complex) -> Constraint[PolynomialElements, complex]: ...
    @overload
    def __le__(self, other: PolynomialElements) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __le__(self, other: Polynomial[PolynomialElements, Scalar]) -> Constraint[PolynomialElements, Scalar]: ...
    @overload
    def __le__(self, other: Polynomial[PolynomialElements, complex]) -> Constraint[PolynomialElements, complex]: ...
    def __hash__(self) -> int: ...

__all__ = [
    "generate_commutative_variables",
    "generate_noncommutative_variables",
    "RewritingStrategy",
]
