"""Type stubs for ``picos.modeling``, PICOS 2.6.2.

Recovered from the installed package: ``Problem``'s signatures from
``inspect.signature``, and its return types by building and solving a problem
in a shell (``add_constraint`` hands the constraint back, ``value`` is a
``float``, ``get_constraint``/``get_variable`` return the stored objects).
"""

from abc import ABC
from collections.abc import Iterable, Mapping
from typing import Any

from picos.constraints import Constraint
from picos.expressions import BaseVariable, Expression, Mutable
from picos.valuable import Valuable

class Objective:
    def __init__(self, direction: str | None = ..., function: Expression | None = ...) -> None: ...
    @property
    def direction(self) -> str: ...
    @property
    def function(self) -> Expression | None: ...

class Options:
    def __init__(self, **options: Any) -> None: ...
    def copy(self) -> Options: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def updated(self, *args: Any, **kwargs: Any) -> Options: ...
    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Solution:
    @property
    def problem(self) -> Problem | None: ...
    @property
    def solver(self) -> str: ...
    @property
    def value(self) -> float: ...
    @property
    def primals(self) -> dict[Any, Any]: ...
    @property
    def duals(self) -> dict[Any, Any]: ...
    @property
    def primalStatus(self) -> str: ...
    @property
    def dualStatus(self) -> str: ...
    @property
    def problemStatus(self) -> str: ...
    @property
    def reportedValue(self) -> float | None: ...
    @property
    def info(self) -> dict[str, Any]: ...
    def apply(self, primals: bool = ..., duals: bool = ..., snapshotStatus: bool = ...) -> None: ...

class SolutionFailure(RuntimeError):
    code: int
    reason: str

class Problem(Valuable, ABC):
    def __init__(
        self,
        name: str | None = ...,
        *,
        copyOptions: Options | None = ...,
        useOptions: Options | None = ...,
        **extra_options: Any,
    ) -> None: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str | None) -> None: ...
    @property
    def objective(self) -> Objective: ...
    @objective.setter
    def objective(self, value: Objective) -> None: ...
    @property
    def options(self) -> Options: ...
    @options.setter
    def options(self, value: Options) -> None: ...
    @property
    def constraints(self) -> Mapping[int, Constraint]: ...
    @property
    def variables(self) -> Mapping[str, BaseVariable]: ...
    @property
    def mutables(self) -> Mapping[str, Mutable]: ...
    @property
    def parameters(self) -> Mapping[str, Mutable]: ...
    @property
    def continuous(self) -> bool: ...
    @property
    def status(self) -> str: ...
    # --- building ---
    def add_constraint(self, constraint: Constraint, key: str | None = ...) -> Constraint: ...
    def add_list_of_constraints(
        self,
        lst: Iterable[Constraint],
        it: Any = ...,
        indices: Any = ...,
        key: str | None = ...,
    ) -> list[Constraint]: ...
    def remove_constraint(self, idOrIndOrCon: Constraint | int) -> None: ...
    def remove_all_constraints(self) -> None: ...
    def set_objective(self, direction: str | None = ..., expression: Expression | Any = ...) -> None: ...
    def require(self, *constraints: Constraint, **kwargs: Any) -> None: ...
    def reset(self, resetOptions: bool = ...) -> None: ...
    def clone(self, copyOptions: bool = ...) -> Problem: ...
    def copy(self) -> Problem: ...
    # --- solving ---
    def solve(self, **extra_options: Any) -> Solution: ...
    def minimize(self, function: Expression, **extra_options: Any) -> Solution: ...
    def maximize(self, function: Expression, **extra_options: Any) -> Solution: ...
    # --- solution access ---
    #
    # `get_variable`/`get_constraint` also accept a name that matches a whole
    # group (`x[0]`, `x[1]`, ...), in which case PICOS returns a `list` or
    # `dict` of them instead. Only the single-object form is typed here, since
    # the two cannot be told apart from the argument.
    def get_variable(self, name: str) -> BaseVariable: ...
    def get_valued_variable(self, name: str) -> Any: ...
    def get_constraint(self, idOrIndOrCon: Constraint | int | tuple[int, ...]) -> Constraint: ...
    def check_current_value_feasibility(self, tol: float = ...) -> tuple[bool, float]: ...
    def write_to_file(self, filename: str, writer: str = ...) -> None: ...
    def as_dual(self) -> Problem: ...
    def conic_form(self) -> Problem: ...

class Footprint: ...
class Specification: ...
class Strategy: ...
class NoStrategyFound(RuntimeError): ...

def maximize(function: Expression, subject_to: Iterable[Constraint] = ..., **options: Any) -> Any: ...
def minimize(function: Expression, subject_to: Iterable[Constraint] = ..., **options: Any) -> Any: ...
def find_assignment(
    constraints: Iterable[Constraint] = ..., variables: Iterable[BaseVariable] = ..., **options: Any
) -> Any: ...
