from ncpoleon.polynomials.noncommutative_polynomials import NonCommutativeOperator as NonCommutativeOperator
from ncpoleon.polynomials.noncommutative_polynomials import (
    generate_noncommutative_variables as generate_noncommutative_variables,
)
