name: CodSpeed Benchmarks

on:
    push:
        branches:
            - "main"
    workflow_run:
        workflows: ["Tests"]
        types:
            - completed
    # `workflow_dispatch` allows CodSpeed to trigger backtest
    # performance analysis in order to generate initial data.
    workflow_dispatch:

jobs:
    benchmarks:
        name: Run benchmarks
        runs-on: ubuntu-latest
        if: >
            github.event_name != 'workflow_run' ||
            (github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.event != 'push')
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
              with:
                  persist-credentials: false
                  repository: ${{ github.event.workflow_run.head_repository.full_name || github.repository }}
                  ref: ${{ github.event.workflow_run.head_sha || github.sha }}
            - name: Install uv
              uses: astral-sh/setup-uv@v8.2.0
            - name: Set up Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
              with:
                  python-version-file: pyproject.toml
            - name: Install dependencies
              run: uv sync --all-extras --dev
            - name: Write MOSEK license
              env:
                  MSK_LICENSE: ${{ secrets.MSK_LICENSE }}
              run: echo "$MSK_LICENSE" > "${{ github.workspace }}/mosek.lic"
            - name: Run the benchmarks
              uses: CodSpeedHQ/action@c145068895e045cc725ee76fcd2307624b65c3af
              env:
                  MOSEKLM_LICENSE_FILE: ${{ github.workspace }}/mosek.lic
              with:
                  mode: simulation
                  run: uv run --config-setting 'build-args=--profile=release' pytest -x --codspeed
